// <copyright file="AssemblyInfo.cs" company="Microsoft">
// Copyright © Microsoft. All Rights Reserved.
// </copyright>

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

#if !UWP
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyCopyright("Copyright © Microsoft. All Rights Reserved.")]
[assembly: ComVisible(false)]
#endif

[assembly: AssemblyDescription("Application Insights SDK Persistence channel")]
[assembly: AssemblyProduct("Application Insights SDK Windows Persistence channel")]
[assembly: InternalsVisibleTo("Microsoft.HockeyApp.PersistenceChannel.Net40.Tests" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.HockeyApp.PersistenceChannel.Net45.Tests" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.HockeyApp.PersistenceChannel.Wrt81.Tests" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.HockeyApp.PersistenceChannel.Wp80.Tests" + AssemblyInfo.PublicKey)]
[assembly: InternalsVisibleTo("Microsoft.HockeyApp.TestFramework" + AssemblyInfo.PublicKey)]

// Assembly dynamically generated by Moq in unit tests
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2" + AssemblyInfo.MoqPublicKey)]